strictness: veryhigh
autodetect: false
max-line-length: 100
pep8: full

pylint:
  options:
    allow-wildcard-with-all: yes
    check-quote-consistency: yes
    max-args: 6
    max-branches: 20
  disable:
    - arguments-differ
    - attribute-defined-outside-init
    - bad-mcs-classmethod-argument
    - broad-except
    - invalid-name
    - no-self-use
    - protected-access
    - too-few-public-methods
    - too-many-public-methods
    - unnecessary-lambda-assignment
    - unused-argument
    - wrong-import-order

pycodestyle:
  disable:
    - E731 # do not assign a lambda expression, use a def
    - N804 # first argument of a classmethod should be named 'cls' (I use 'mcls' for metaclasses)

pyflakes:
  disable:
    - F401 # `module` imported but unused
    - F403 # 'from `module` import *' used; unable to detect undefined names
    - F405 # `name` may be undefined, or defined from star imports: `module`
