autodetect: false
max-line-length: 100
pep8: full

pylint:
  disable:
    - bad-continuation
    - cell-var-from-loop
    - inconsistent-return-statements
    - invalid-name
    - line-too-long
    - missing-docstring
    - missing-final-newline
    - mixed-indentation
    - no-member
    - unused-wildcard-import
    - wildcard-import
    - wrong-import-order

pycodestyle:
  disable:
    - E203
    - E402
    - E501
    - E722
    - E731
    - E741
    - F403
    - F405
    - W503
