name: Test

on:
  push: {branches: [master]}
  pull_request: {branches: [master]}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with: {python-version: 3.9}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
      - name: Run tests
        env: {token: "${{ secrets.token }}"}
        run: >
          tests() { for test in ./tests/[^_]*; do python -m
          tests.`basename "$test" .py` || return; done }; tests
